[package]
name = "selendra-overseer-all-subsystems-gen"
version = "0.1.1"
authors = ["Selendra <info@selendra.org>"]
edition = "2018"
description = "Small proc macro to create mocking level iface type helpers"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.60", features = ["full", "extra-traits"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"
assert_matches = "1.5.0"

[dev-dependencies]
trybuild = "1.0.42"
