[package]
name = "xcm-executor"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
description = "An abstract and configurable XCM message executor."
edition = "2018"

[dependencies]
impl-trait-for-tuples = "0.2.0"
parity-scale-codec = { version = "1.3.5", default-features = false, features = ["derive"] }

sp-std = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-io = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-arithmetic = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-core = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
sp-runtime = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }
frame-support = { git = "https://github.com/selendra/substrate", branch = "v2.0.1", default-features = false }

xcm = { path = "..", default-features = false }
[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"xcm/std",
	"sp-std/std",
	"sp-io/std",
	"sp-arithmetic/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
]
