[package]
name = "test-parachain-halt"
version = "0.1.3"
authors = ["Selendra <info@selendra.org>"]
description = "Test parachain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }

[features]
default = [ "std" ]
std = []
